// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDKFiB39JYsPkk3d0qhm7EQ9ywtpV8p2w',
    appId: '1:182613329187:web:89fdfe43a1931ede167896',
    messagingSenderId: '182613329187',
    projectId: 'flutter-login-b7e20',
    authDomain: 'flutter-login-b7e20.firebaseapp.com',
    storageBucket: 'flutter-login-b7e20.firebasestorage.app',
    measurementId: 'G-1R3YDG3B43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACO1I_ZPyd1v53H7asJD4SlqqMOlwGmTQ',
    appId: '1:182613329187:android:bbb933ffd6b4c0a1167896',
    messagingSenderId: '182613329187',
    projectId: 'flutter-login-b7e20',
    storageBucket: 'flutter-login-b7e20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxE2X7e7qRikpI4hgu1DBTr-04_-am9Q',
    appId: '1:182613329187:ios:0d2d3de93ec77a0c167896',
    messagingSenderId: '182613329187',
    projectId: 'flutter-login-b7e20',
    storageBucket: 'flutter-login-b7e20.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjxE2X7e7qRikpI4hgu1DBTr-04_-am9Q',
    appId: '1:182613329187:ios:0d2d3de93ec77a0c167896',
    messagingSenderId: '182613329187',
    projectId: 'flutter-login-b7e20',
    storageBucket: 'flutter-login-b7e20.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDKFiB39JYsPkk3d0qhm7EQ9ywtpV8p2w',
    appId: '1:182613329187:web:b8a7d76155fc16fc167896',
    messagingSenderId: '182613329187',
    projectId: 'flutter-login-b7e20',
    authDomain: 'flutter-login-b7e20.firebaseapp.com',
    storageBucket: 'flutter-login-b7e20.firebasestorage.app',
    measurementId: 'G-QML9XFZZBJ',
  );
}
